version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: himanshu277/careerhub-frontend
    container_name: careerhub-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
